version: "3.9"
services:
  web:
    container_name: bike-map-app
    build:
      context: bike-map-app
      args:
        GMAPS_API_KEY: <<Placeholder for GMAPS API KEY>>
    ports:
      - "4200:4200"
    networks:
      - app-network
  api:
    container_name: bike-map-api
    build:
      context: bike-rental-golang-api
    ports:
      - "8080:8080"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge